Environment:
	Python: 3.12.8
	PyTorch: 2.6.0+cu124
	CUDA: 12.4
	CUDNN: 90100
	NumPy: 2.2.2
	PIL: 11.1.0
Args:
	algorithm: ERM
	checkpoint_freq: None
	data_dir: .
	dataset: AbRosetta
	holdout_fraction: 0.2
	hparams: None
	hparams_seed: 0
	init_step: False
	output_dir: outputs
	path_for_init: None
	save_model_every_checkpoint: False
	seed: 0
	skip_model_save: False
	steps: None
	target: None
	task: domain_generalization
	test_envs: [0]
	trial_seed: 0
	uda_holdout_fraction: 0
	use_esm: False
HParams:
	add_noise: False
	batch_size: 32
	class_balanced: False
	data_augmentation: True
	lr: 5e-05
	nonlinear_classifier: False
	resnet18: True
	resnet_dropout: 0.0
	weight_decay: 0.0
Device:  cuda
Error loading the dataset, was it downloaded?
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/hpc/group/naderilab/imt11/antibody-domainbed/domainbed/scripts/train.py", line 169, in <module>
    algorithm = algorithm_class(dataset.input_shape, dataset.num_classes,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/naderilab/imt11/antibody-domainbed/domainbed/algorithms.py", line 99, in __init__
    self.featurizer = networks.Featurizer(input_shape, self.hparams)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/naderilab/imt11/antibody-domainbed/domainbed/networks.py", line 59, in Featurizer
    return SeqCNN(input_shape[0], hparams)
                  ~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
Environment:
	Python: 3.12.8
	PyTorch: 2.6.0+cu124
	CUDA: 12.4
	CUDNN: 90100
	NumPy: 2.2.2
	PIL: 11.1.0
Args:
	algorithm: ERM
	checkpoint_freq: None
	data_dir: .
	dataset: AbRosetta
	holdout_fraction: 0.2
	hparams: None
	hparams_seed: 0
	init_step: False
	output_dir: outputs
	path_for_init: None
	save_model_every_checkpoint: False
	seed: 0
	skip_model_save: False
	steps: None
	target: None
	task: domain_generalization
	test_envs: [0]
	trial_seed: 0
	uda_holdout_fraction: 0
	use_esm: False
HParams:
	add_noise: False
	batch_size: 32
	class_balanced: False
	data_augmentation: True
	lr: 5e-05
	nonlinear_classifier: False
	resnet18: True
	resnet_dropout: 0.0
	weight_decay: 0.0
Device:  cuda
Error loading the dataset, was it downloaded?
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/hpc/group/naderilab/imt11/antibody-domainbed/domainbed/scripts/train.py", line 169, in <module>
    algorithm = algorithm_class(dataset.input_shape, dataset.num_classes,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/naderilab/imt11/antibody-domainbed/domainbed/algorithms.py", line 99, in __init__
    self.featurizer = networks.Featurizer(input_shape, self.hparams)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/naderilab/imt11/antibody-domainbed/domainbed/networks.py", line 59, in Featurizer
    return SeqCNN(input_shape[0], hparams)
                  ~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
Environment:
	Python: 3.12.8
	PyTorch: 2.6.0+cu124
	CUDA: 12.4
	CUDNN: 90100
	NumPy: 2.2.2
	PIL: 11.1.0
Args:
	algorithm: ERM
	checkpoint_freq: None
	data_dir: .
	dataset: AbRosetta
	holdout_fraction: 0.2
	hparams: None
	hparams_seed: 0
	init_step: False
	output_dir: outputs
	path_for_init: None
	save_model_every_checkpoint: False
	seed: 0
	skip_model_save: False
	steps: None
	target: None
	task: domain_generalization
	test_envs: [0]
	trial_seed: 0
	uda_holdout_fraction: 0
	use_esm: False
HParams:
	add_noise: False
	batch_size: 32
	class_balanced: False
	data_augmentation: True
	lr: 5e-05
	nonlinear_classifier: False
	resnet18: True
	resnet_dropout: 0.0
	weight_decay: 0.0
Device:  cuda
Loading dataset from domainbed/data/abdb.csv
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/hpc/group/naderilab/imt11/antibody-domainbed/domainbed/scripts/train.py", line 111, in <module>
    dataset = vars(datasets)[args.dataset](
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/naderilab/imt11/antibody-domainbed/domainbed/datasets.py", line 181, in __init__
    df.drop_duplicates(subset=['seqid'], inplace=True, keep='last')
  File "/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/site-packages/pandas/core/frame.py", line 6818, in drop_duplicates
    result = self[-self.duplicated(subset, keep=keep)]
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/site-packages/pandas/core/frame.py", line 6950, in duplicated
    raise KeyError(Index(diff))
KeyError: Index(['seqid'], dtype='object')
Environment:
	Python: 3.12.8
	PyTorch: 2.6.0+cu124
	CUDA: 12.4
	CUDNN: 90100
	NumPy: 2.2.2
	PIL: 11.1.0
Args:
	algorithm: ERM
	checkpoint_freq: None
	data_dir: .
	dataset: AbRosetta
	holdout_fraction: 0.2
	hparams: None
	hparams_seed: 0
	init_step: False
	output_dir: outputs/
	path_for_init: None
	save_model_every_checkpoint: False
	seed: 0
	skip_model_save: False
	steps: None
	target: None
	task: domain_generalization
	test_envs: [0]
	trial_seed: 0
	uda_holdout_fraction: 0
	use_esm: False
HParams:
	add_noise: False
	batch_size: 32
	class_balanced: False
	data_augmentation: True
	lr: 5e-05
	nonlinear_classifier: False
	resnet18: True
	resnet_dropout: 0.0
	weight_decay: 0.0
Device:  cuda
Loading dataset from domainbed/data/abdb.csv
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/hpc/group/naderilab/imt11/antibody-domainbed/domainbed/scripts/train.py", line 111, in <module>
    dataset = vars(datasets)[args.dataset](
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/naderilab/imt11/antibody-domainbed/domainbed/datasets.py", line 181, in __init__
    df.drop_duplicates(subset=['seqid'], inplace=True, keep='last')
  File "/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/site-packages/pandas/core/frame.py", line 6818, in drop_duplicates
    result = self[-self.duplicated(subset, keep=keep)]
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/site-packages/pandas/core/frame.py", line 6950, in duplicated
    raise KeyError(Index(diff))
KeyError: Index(['seqid'], dtype='object')
Environment:
	Python: 3.12.8
	PyTorch: 2.6.0+cu124
	CUDA: 12.4
	CUDNN: 90100
	NumPy: 2.2.2
	PIL: 11.1.0
Args:
	algorithm: ERM
	checkpoint_freq: None
	data_dir: .
	dataset: AbRosetta
	holdout_fraction: 0.2
	hparams: None
	hparams_seed: 0
	init_step: False
	output_dir: outputs/
	path_for_init: None
	save_model_every_checkpoint: False
	seed: 0
	skip_model_save: False
	steps: None
	target: None
	task: domain_generalization
	test_envs: [0]
	trial_seed: 0
	uda_holdout_fraction: 0
	use_esm: False
HParams:
	add_noise: False
	batch_size: 32
	class_balanced: False
	data_augmentation: True
	lr: 5e-05
	nonlinear_classifier: False
	resnet18: True
	resnet_dropout: 0.0
	weight_decay: 0.0
Device:  cuda
Loading dataset from domainbed/data/abdb.csv
env   target    
env0  HIV1           184
      SARS_CoV_2    1117
env1  HIV1           778
      SARS_CoV_2    3095
env2  HIV1           275
      SARS_CoV_2    1469
env3  HIV1           548
      SARS_CoV_2    3140
Name: target, dtype: int64
Traceback (most recent call last):
  File "/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'ag_wt'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/hpc/group/naderilab/imt11/antibody-domainbed/domainbed/scripts/train.py", line 111, in <module>
    dataset = vars(datasets)[args.dataset](
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/naderilab/imt11/antibody-domainbed/domainbed/datasets.py", line 189, in __init__
    target_len = df['ag_wt'].apply(len)
                 ~~^^^^^^^^^
  File "/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/site-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'ag_wt'
Environment:
	Python: 3.12.8
	PyTorch: 2.6.0+cu124
	CUDA: 12.4
	CUDNN: 90100
	NumPy: 2.2.2
	PIL: 11.1.0
Args:
	algorithm: ERM
	checkpoint_freq: None
	data_dir: .
	dataset: AbRosetta
	holdout_fraction: 0.2
	hparams: None
	hparams_seed: 0
	init_step: False
	output_dir: outputs/
	path_for_init: None
	save_model_every_checkpoint: False
	seed: 0
	skip_model_save: False
	steps: None
	target: None
	task: domain_generalization
	test_envs: [0]
	trial_seed: 0
	uda_holdout_fraction: 0
	use_esm: False
HParams:
	add_noise: False
	batch_size: 32
	class_balanced: False
	data_augmentation: True
	lr: 5e-05
	nonlinear_classifier: False
	resnet18: True
	resnet_dropout: 0.0
	weight_decay: 0.0
Device:  cuda
Loading dataset from domainbed/data/abdb.csv
env   target    
env0  HIV1           184
      SARS_CoV_2    1117
env1  HIV1           778
      SARS_CoV_2    3095
env2  HIV1           275
      SARS_CoV_2    1469
env3  HIV1           548
      SARS_CoV_2    3140
Name: target, dtype: int64
env   target      is_binder
env0  HIV1        False          89
                  True           95
      SARS_CoV_2  False         577
                  True          540
env1  HIV1        False         226
                  True          552
      SARS_CoV_2  False        1347
                  True         1748
env2  HIV1        False         132
                  True          143
      SARS_CoV_2  False         930
                  True          539
env3  HIV1        False         233
                  True          315
      SARS_CoV_2  False        1516
                  True         1624
Name: is_binder, dtype: int64
(10606, 16)
['env0' 'env1' 'env2' 'env3']
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/hpc/group/naderilab/imt11/antibody-domainbed/domainbed/scripts/train.py", line 195, in <module>
    train_loaders = [InfiniteDataLoader(
                     ^^^^^^^^^^^^^^^^^^^
TypeError: InfiniteDataLoader.__init__() got an unexpected keyword argument 'collate_fn'
/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/tempfile.py:936: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/tmpsll8j66_'>
  _warnings.warn(warn_message, ResourceWarning)
Environment:
	Python: 3.12.8
	PyTorch: 2.6.0+cu124
	CUDA: 12.4
	CUDNN: 90100
	NumPy: 2.2.2
	PIL: 11.1.0
Args:
	algorithm: ERM
	checkpoint_freq: None
	data_dir: .
	dataset: AbRosetta
	holdout_fraction: 0.2
	hparams: None
	hparams_seed: 0
	init_step: False
	output_dir: outputs/
	path_for_init: None
	save_model_every_checkpoint: False
	seed: 0
	skip_model_save: False
	steps: None
	target: None
	task: domain_generalization
	test_envs: [0]
	trial_seed: 0
	uda_holdout_fraction: 0
	use_esm: False
HParams:
	add_noise: False
	batch_size: 32
	class_balanced: False
	data_augmentation: True
	lr: 5e-05
	nonlinear_classifier: False
	resnet18: True
	resnet_dropout: 0.0
	weight_decay: 0.0
Device:  cuda
Loading dataset from domainbed/data/abdb.csv
env   target    
env0  HIV1           184
      SARS_CoV_2    1117
env1  HIV1           778
      SARS_CoV_2    3095
env2  HIV1           275
      SARS_CoV_2    1469
env3  HIV1           548
      SARS_CoV_2    3140
Name: target, dtype: int64
env   target      is_binder
env0  HIV1        False          89
                  True           95
      SARS_CoV_2  False         577
                  True          540
env1  HIV1        False         226
                  True          552
      SARS_CoV_2  False        1347
                  True         1748
env2  HIV1        False         132
                  True          143
      SARS_CoV_2  False         930
                  True          539
env3  HIV1        False         233
                  True          315
      SARS_CoV_2  False        1516
                  True         1624
Name: is_binder, dtype: int64
(10606, 16)
['env0' 'env1' 'env2' 'env3']
/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=482895) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=482895) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=482895) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=482895) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=482895) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=482895) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=482895) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=482895) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=482895) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=482895) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=482895) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/hpc/group/naderilab/imt11/antibody-domainbed/domainbed/scripts/train.py", line 284, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/naderilab/imt11/antibody-domainbed/domainbed/algorithms.py", line 133, in update
    loss = F.cross_entropy(self.predict(all_x), all_y)
                           ^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/naderilab/imt11/antibody-domainbed/domainbed/algorithms.py", line 142, in predict
    return self.network(x)
           ^^^^^^^^^^^^^^^
  File "/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/site-packages/torch/nn/modules/container.py", line 250, in forward
    input = module(input)
            ^^^^^^^^^^^^^
  File "/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/naderilab/imt11/antibody-domainbed/domainbed/networks.py", line 148, in forward
    h_ab = self.conv_layers(e_ab.permute(0, 2, 1))  # (batch_size, dim, L)
                            ^^^^^^^^^^^^^^^^^^^^^
RuntimeError: permute(sparse_coo): number of dimensions in the tensor input does not match the length of the desired ordering of dimensions i.e. input.dim() = 4 is not equal to len(dims) = 3
/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/tempfile.py:936: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/tmpv26b6gjs'>
  _warnings.warn(warn_message, ResourceWarning)
Environment:
	Python: 3.12.8
	PyTorch: 2.6.0+cu124
	CUDA: 12.4
	CUDNN: 90100
	NumPy: 2.2.2
	PIL: 11.1.0
Args:
	algorithm: ERM
	checkpoint_freq: None
	data_dir: .
	dataset: AbRosetta
	holdout_fraction: 0.2
	hparams: None
	hparams_seed: 0
	init_step: False
	output_dir: outputs/
	path_for_init: None
	save_model_every_checkpoint: False
	seed: 0
	skip_model_save: False
	steps: None
	target: None
	task: domain_generalization
	test_envs: [0]
	trial_seed: 0
	uda_holdout_fraction: 0
	use_esm: False
HParams:
	add_noise: False
	batch_size: 32
	class_balanced: False
	data_augmentation: True
	lr: 5e-05
	nonlinear_classifier: False
	resnet18: True
	resnet_dropout: 0.0
	weight_decay: 0.0
Device:  cuda
Loading dataset from domainbed/data/abdb.csv
env   target    
env0  HIV1           184
      SARS_CoV_2    1117
env1  HIV1           778
      SARS_CoV_2    3095
env2  HIV1           275
      SARS_CoV_2    1469
env3  HIV1           548
      SARS_CoV_2    3140
Name: target, dtype: int64
env   target      is_binder
env0  HIV1        False          89
                  True           95
      SARS_CoV_2  False         577
                  True          540
env1  HIV1        False         226
                  True          552
      SARS_CoV_2  False        1347
                  True         1748
env2  HIV1        False         132
                  True          143
      SARS_CoV_2  False         930
                  True          539
env3  HIV1        False         233
                  True          315
      SARS_CoV_2  False        1516
                  True         1624
Name: is_binder, dtype: int64
(10606, 16)
['env0' 'env1' 'env2' 'env3']
/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=483985) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=483985) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=483985) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=483985) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=483985) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=483985) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=483985) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=483985) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=483985) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=483985) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=483985) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
[DEBUG] Input tensor shape: torch.Size([96, 1213, 22]), dimensions: 3
[DEBUG] Splitting into antibody and antigen
[DEBUG] Antibody tensor: torch.Size([96, 298, 22]), Antigen tensor: torch.Size([96, 915, 22])
[DEBUG] Creating embeddings
[DEBUG] Antibody embedding: torch.Size([96, 298, 64]), Antigen embedding: torch.Size([96, 915, 64])
[DEBUG] Before permute - Antibody embedding: torch.Size([96, 298, 64])
[DEBUG] After permute - Antibody: torch.Size([96, 64, 298])
[DEBUG] Before permute - Antigen embedding: torch.Size([96, 915, 64])
[DEBUG] After permute - Antigen: torch.Size([96, 64, 915])
[DEBUG] After conv - Antibody: torch.Size([96, 128, 71]), Antigen: torch.Size([96, 128, 225])
[DEBUG] After pooling - Antibody: torch.Size([96, 128]), Antigen: torch.Size([96, 128])
[DEBUG] After concatenation: torch.Size([96, 256])
[DEBUG] Final output: torch.Size([96, 256])
[DEBUG] Input tensor shape: torch.Size([32, 1213, 22]), dimensions: 3
[DEBUG] Splitting into antibody and antigen
[DEBUG] Antibody tensor: torch.Size([32, 298, 22]), Antigen tensor: torch.Size([32, 915, 22])
[DEBUG] Creating embeddings
[DEBUG] Antibody embedding: torch.Size([32, 298, 64]), Antigen embedding: torch.Size([32, 915, 64])
[DEBUG] Before permute - Antibody embedding: torch.Size([32, 298, 64])
[DEBUG] After permute - Antibody: torch.Size([32, 64, 298])
[DEBUG] Before permute - Antigen embedding: torch.Size([32, 915, 64])
[DEBUG] After permute - Antigen: torch.Size([32, 64, 915])
[DEBUG] After conv - Antibody: torch.Size([32, 128, 71]), Antigen: torch.Size([32, 128, 225])
[DEBUG] After pooling - Antibody: torch.Size([32, 128]), Antigen: torch.Size([32, 128])
[DEBUG] After concatenation: torch.Size([32, 256])
[DEBUG] Final output: torch.Size([32, 256])
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/hpc/group/naderilab/imt11/antibody-domainbed/domainbed/scripts/train.py", line 301, in <module>
    acc = misc.accuracy(algorithm, loader, weights, device)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/naderilab/imt11/antibody-domainbed/domainbed/lib/misc.py", line 232, in accuracy
    correct += (p.argmax(1).eq(y).float() * batch_weights).sum().item()
                ^^^^^^^^^^^^^^^^^
RuntimeError: The size of tensor a (32) must match the size of tensor b (2) at non-singleton dimension 1
/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/tempfile.py:936: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/tmpkkv1zrt7'>
  _warnings.warn(warn_message, ResourceWarning)
Environment:
	Python: 3.12.8
	PyTorch: 2.6.0+cu124
	CUDA: 12.4
	CUDNN: 90100
	NumPy: 2.2.2
	PIL: 11.1.0
Args:
	algorithm: ERM
	checkpoint_freq: None
	data_dir: .
	dataset: AbRosetta
	holdout_fraction: 0.2
	hparams: None
	hparams_seed: 0
	init_step: False
	output_dir: outputs/
	path_for_init: None
	save_model_every_checkpoint: False
	seed: 0
	skip_model_save: False
	steps: None
	target: None
	task: domain_generalization
	test_envs: [0]
	trial_seed: 0
	uda_holdout_fraction: 0
	use_esm: False
HParams:
	add_noise: False
	batch_size: 32
	class_balanced: False
	data_augmentation: True
	lr: 5e-05
	nonlinear_classifier: False
	resnet18: True
	resnet_dropout: 0.0
	weight_decay: 0.0
Device:  cuda
Loading dataset from domainbed/data/abdb.csv
env   target    
env0  HIV1           184
      SARS_CoV_2    1117
env1  HIV1           778
      SARS_CoV_2    3095
env2  HIV1           275
      SARS_CoV_2    1469
env3  HIV1           548
      SARS_CoV_2    3140
Name: target, dtype: int64
env   target      is_binder
env0  HIV1        False          89
                  True           95
      SARS_CoV_2  False         577
                  True          540
env1  HIV1        False         226
                  True          552
      SARS_CoV_2  False        1347
                  True         1748
env2  HIV1        False         132
                  True          143
      SARS_CoV_2  False         930
                  True          539
env3  HIV1        False         233
                  True          315
      SARS_CoV_2  False        1516
                  True         1624
Name: is_binder, dtype: int64
(10606, 16)
['env0' 'env1' 'env2' 'env3']
/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=485471) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=485471) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=485471) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=485471) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=485471) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=485471) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=485471) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=485471) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=485471) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=485471) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=485471) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
[DEBUG] Input tensor shape: torch.Size([96, 1213, 22]), dimensions: 3
[DEBUG] Splitting into antibody and antigen
[DEBUG] Antibody tensor: torch.Size([96, 298, 22]), Antigen tensor: torch.Size([96, 915, 22])
[DEBUG] Creating embeddings
[DEBUG] Antibody embedding: torch.Size([96, 298, 64]), Antigen embedding: torch.Size([96, 915, 64])
[DEBUG] Before permute - Antibody embedding: torch.Size([96, 298, 64])
[DEBUG] After permute - Antibody: torch.Size([96, 64, 298])
[DEBUG] Before permute - Antigen embedding: torch.Size([96, 915, 64])
[DEBUG] After permute - Antigen: torch.Size([96, 64, 915])
[DEBUG] After conv - Antibody: torch.Size([96, 128, 71]), Antigen: torch.Size([96, 128, 225])
[DEBUG] After pooling - Antibody: torch.Size([96, 128]), Antigen: torch.Size([96, 128])
[DEBUG] After concatenation: torch.Size([96, 256])
[DEBUG] Final output: torch.Size([96, 256])
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/hpc/group/naderilab/imt11/antibody-domainbed/domainbed/scripts/train.py", line 284, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/naderilab/imt11/antibody-domainbed/domainbed/algorithms.py", line 133, in update
    loss = F.cross_entropy(self.predict(all_x), all_y)
                           ^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/naderilab/imt11/antibody-domainbed/domainbed/algorithms.py", line 142, in predict
    return self.network(x)
           ^^^^^^^^^^^^^^^
  File "/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/site-packages/torch/nn/modules/container.py", line 250, in forward
    input = module(input)
            ^^^^^^^^^^^^^
  File "/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/site-packages/torch/nn/modules/linear.py", line 125, in forward
    return F.linear(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: mat1 and mat2 shapes cannot be multiplied (96x2 and 256x2)
/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/tempfile.py:936: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/tmpy0b591pp'>
  _warnings.warn(warn_message, ResourceWarning)
Environment:
	Python: 3.12.8
	PyTorch: 2.6.0+cu124
	CUDA: 12.4
	CUDNN: 90100
	NumPy: 2.2.2
	PIL: 11.1.0
Args:
	algorithm: ERM
	checkpoint_freq: None
	data_dir: .
	dataset: AbRosetta
	holdout_fraction: 0.2
	hparams: None
	hparams_seed: 0
	init_step: False
	output_dir: outputs/
	path_for_init: None
	save_model_every_checkpoint: False
	seed: 0
	skip_model_save: False
	steps: None
	target: None
	task: domain_generalization
	test_envs: [0]
	trial_seed: 0
	uda_holdout_fraction: 0
	use_esm: False
HParams:
	add_noise: False
	batch_size: 32
	class_balanced: False
	data_augmentation: True
	lr: 5e-05
	nonlinear_classifier: False
	resnet18: True
	resnet_dropout: 0.0
	weight_decay: 0.0
Device:  cuda
Loading dataset from domainbed/data/abdb.csv
env   target    
env0  HIV1           184
      SARS_CoV_2    1117
env1  HIV1           778
      SARS_CoV_2    3095
env2  HIV1           275
      SARS_CoV_2    1469
env3  HIV1           548
      SARS_CoV_2    3140
Name: target, dtype: int64
env   target      is_binder
env0  HIV1        False          89
                  True           95
      SARS_CoV_2  False         577
                  True          540
env1  HIV1        False         226
                  True          552
      SARS_CoV_2  False        1347
                  True         1748
env2  HIV1        False         132
                  True          143
      SARS_CoV_2  False         930
                  True          539
env3  HIV1        False         233
                  True          315
      SARS_CoV_2  False        1516
                  True         1624
Name: is_binder, dtype: int64
(10606, 16)
['env0' 'env1' 'env2' 'env3']
/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=485889) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=485889) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=485889) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=485889) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=485889) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=485889) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=485889) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=485889) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=485889) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=485889) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=485889) is multi-threaded, use of fork() may lead to deadlocks in the child.
  self.pid = os.fork()
[DEBUG] Input tensor shape: torch.Size([96, 1213, 22]), dimensions: 3
[DEBUG] Input tensor shape: torch.Size([32, 1213, 22]), dimensions: 3
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/hpc/group/naderilab/imt11/antibody-domainbed/domainbed/scripts/train.py", line 301, in <module>
    acc = misc.accuracy(algorithm, loader, weights, device)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/naderilab/imt11/antibody-domainbed/domainbed/lib/misc.py", line 232, in accuracy
    correct += (p.argmax(1).eq(y).float() * batch_weights).sum().item()
                ^^^^^^^^^^^^^^^^^
RuntimeError: The size of tensor a (32) must match the size of tensor b (2) at non-singleton dimension 1
/hpc/group/naderilab/imt11/Miniconda3/lib/python3.12/tempfile.py:936: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/tmpl6izycjo'>
  _warnings.warn(warn_message, ResourceWarning)
